# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import quest_pb2 as quest__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemicRiskOracleStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    SystemicRiskOracle
    Servicio principal del risk-engine. Recibe el estado de un epoch de Ethereum
    y retorna el Grey Zone Score + clasificación de riesgo macroprudencial.
    ─────────────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateGreyZoneScore = channel.unary_unary(
                '/quest.v1.SystemicRiskOracle/CalculateGreyZoneScore',
                request_serializer=quest__pb2.EpochRequest.SerializeToString,
                response_deserializer=quest__pb2.GreyZoneResponse.FromString,
                _registered_method=True)


class SystemicRiskOracleServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    SystemicRiskOracle
    Servicio principal del risk-engine. Recibe el estado de un epoch de Ethereum
    y retorna el Grey Zone Score + clasificación de riesgo macroprudencial.
    ─────────────────────────────────────────────────────────────────────────────
    """

    def CalculateGreyZoneScore(self, request, context):
        """Calcula el Grey Zone Score para un epoch dado.
        Grey Zone Score = gross_slashing_loss / (cl_rewards + mev_rewards)
        Un score >= 0.5 indica riesgo latente que safe_border.py de Lido no detecta.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemicRiskOracleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateGreyZoneScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateGreyZoneScore,
                    request_deserializer=quest__pb2.EpochRequest.FromString,
                    response_serializer=quest__pb2.GreyZoneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quest.v1.SystemicRiskOracle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quest.v1.SystemicRiskOracle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemicRiskOracle(object):
    """─────────────────────────────────────────────────────────────────────────────
    SystemicRiskOracle
    Servicio principal del risk-engine. Recibe el estado de un epoch de Ethereum
    y retorna el Grey Zone Score + clasificación de riesgo macroprudencial.
    ─────────────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def CalculateGreyZoneScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quest.v1.SystemicRiskOracle/CalculateGreyZoneScore',
            quest__pb2.EpochRequest.SerializeToString,
            quest__pb2.GreyZoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
