# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquest.proto\x12\x08quest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc6\x03\n\x0c\x45pochRequest\x12\r\n\x05\x65poch\x18\x01 \x01(\x04\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10total_validators\x18\x03 \x01(\x04\x12!\n\x19total_active_balance_gwei\x18\x04 \x01(\x04\x12\x1a\n\x12slashed_validators\x18\x05 \x01(\r\x12\x1d\n\x15slashing_penalty_gwei\x18\x06 \x01(\x04\x12\x37\n\x12\x65poch_rewards_gwei\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x1a\n\x12participation_rate\x18\x08 \x01(\x01\x12\x14\n\x0c\x62lock_number\x18\t \x01(\x04\x12\x1a\n\x12\x61vg_gas_price_gwei\x18\n \x01(\x01\x12\x17\n\x0f\x62urned_eth_gwei\x18\x0b \x01(\x04\x12\x14\n\x0clido_tvl_eth\x18\x0c \x01(\x01\x12\x34\n\x0fnet_rebase_gwei\x18\r \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x14\n\x0cis_grey_zone\x18\x0e \x01(\x08\"\xca\x01\n\x10GreyZoneResponse\x12\r\n\x05\x65poch\x18\x01 \x01(\x04\x12\x1f\n\x17gross_slashing_loss_eth\x18\x02 \x01(\x01\x12\x16\n\x0e\x63l_rewards_eth\x18\x03 \x01(\x01\x12\x12\n\nburned_eth\x18\x04 \x01(\x01\x12\x17\n\x0fgrey_zone_score\x18\x05 \x01(\x01\x12\'\n\nrisk_level\x18\x06 \x01(\x0e\x32\x13.quest.v1.RiskLevel\x12\x18\n\x10has_rewards_data\x18\x07 \x01(\x08*r\n\tRiskLevel\x12\x1a\n\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x16\n\x12RISK_LEVEL_HEALTHY\x10\x01\x12\x18\n\x14RISK_LEVEL_GREY_ZONE\x10\x02\x12\x17\n\x13RISK_LEVEL_CRITICAL\x10\x03\x32\x62\n\x12SystemicRiskOracle\x12L\n\x16\x43\x61lculateGreyZoneScore\x12\x16.quest.v1.EpochRequest\x1a\x1a.quest.v1.GreyZoneResponseB6Z4github.com/quest-protocol/quest/gen/quest/v1;questv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/quest-protocol/quest/gen/quest/v1;questv1'
  _globals['_RISKLEVEL']._serialized_start=752
  _globals['_RISKLEVEL']._serialized_end=866
  _globals['_EPOCHREQUEST']._serialized_start=91
  _globals['_EPOCHREQUEST']._serialized_end=545
  _globals['_GREYZONERESPONSE']._serialized_start=548
  _globals['_GREYZONERESPONSE']._serialized_end=750
  _globals['_SYSTEMICRISKORACLE']._serialized_start=868
  _globals['_SYSTEMICRISKORACLE']._serialized_end=966
# @@protoc_insertion_point(module_scope)
