steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - api/Dockerfile
      - -t
      - gcr.io/quest-493015/quest-api:latest
      - .
images:
  - gcr.io/quest-493015/quest-api:latest
